services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: framework-setisd-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: always
