"""fase1 triagem macroscopia: paciente_local, exame, frasco, cassete, macroscopia, historico

Revision ID: 05efce119b89
Revises: 8a2efbe37bb6
Create Date: 2026-06-23 14:39:25.519121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05efce119b89'
down_revision: Union[str, Sequence[str], None] = '8a2efbe37bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes_local',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('cns', sa.String(length=15), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_local_cns'), 'pacientes_local', ['cns'], unique=True)
    op.create_index(op.f('ix_pacientes_local_cpf'), 'pacientes_local', ['cpf'], unique=True)
    op.create_table('exames',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('numero_solicitacao', sa.String(), nullable=False),
    sa.Column('id_paciente', sa.String(), nullable=False),
    sa.Column('numero_exame_aghu', sa.String(), nullable=True),
    sa.Column('tipo_peca', sa.String(), nullable=True),
    sa.Column('topografia', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_recebimento', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes_local.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exames_id_paciente'), 'exames', ['id_paciente'], unique=False)
    op.create_index(op.f('ix_exames_numero_solicitacao'), 'exames', ['numero_solicitacao'], unique=True)
    op.create_table('frascos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_exame', sa.String(), nullable=False),
    sa.Column('codigo_interno', sa.String(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('descricao_macroscopia', sa.Text(), nullable=True),
    sa.Column('numero_cassetes_gerados', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_exame'], ['exames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frascos_codigo_interno'), 'frascos', ['codigo_interno'], unique=True)
    op.create_index(op.f('ix_frascos_id_exame'), 'frascos', ['id_exame'], unique=False)
    op.create_index(op.f('ix_frascos_qr_code'), 'frascos', ['qr_code'], unique=True)
    op.create_table('cassetes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_frasco', sa.String(), nullable=False),
    sa.Column('letra_fragmento', sa.String(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.Column('coloracao_padrao', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_frasco'], ['frascos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_frasco', 'letra_fragmento', name='uq_cassete_frasco_letra')
    )
    op.create_index(op.f('ix_cassetes_id_frasco'), 'cassetes', ['id_frasco'], unique=False)
    op.create_index(op.f('ix_cassetes_qr_code'), 'cassetes', ['qr_code'], unique=True)
    op.create_table('macroscopias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_frasco', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_realizacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('responsavel', sa.String(), nullable=True),
    sa.Column('numero_cassetes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_frasco'], ['frascos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macroscopias_id_frasco'), 'macroscopias', ['id_frasco'], unique=False)
    op.create_table('historico_movimentacao',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_exame', sa.String(), nullable=True),
    sa.Column('id_frasco', sa.String(), nullable=True),
    sa.Column('id_cassete', sa.String(), nullable=True),
    sa.Column('etapa', sa.String(length=50), nullable=False),
    sa.Column('status_anterior', sa.String(), nullable=True),
    sa.Column('status_novo', sa.String(), nullable=False),
    sa.Column('usuario_responsavel', sa.String(), nullable=True),
    sa.Column('timestamp_transicao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ip_origem', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cassete'], ['cassetes.id'], ),
    sa.ForeignKeyConstraint(['id_exame'], ['exames.id'], ),
    sa.ForeignKeyConstraint(['id_frasco'], ['frascos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_movimentacao_id_cassete'), 'historico_movimentacao', ['id_cassete'], unique=False)
    op.create_index(op.f('ix_historico_movimentacao_id_exame'), 'historico_movimentacao', ['id_exame'], unique=False)
    op.create_index(op.f('ix_historico_movimentacao_id_frasco'), 'historico_movimentacao', ['id_frasco'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_movimentacao_id_frasco'), table_name='historico_movimentacao')
    op.drop_index(op.f('ix_historico_movimentacao_id_exame'), table_name='historico_movimentacao')
    op.drop_index(op.f('ix_historico_movimentacao_id_cassete'), table_name='historico_movimentacao')
    op.drop_table('historico_movimentacao')
    op.drop_index(op.f('ix_macroscopias_id_frasco'), table_name='macroscopias')
    op.drop_table('macroscopias')
    op.drop_index(op.f('ix_cassetes_qr_code'), table_name='cassetes')
    op.drop_index(op.f('ix_cassetes_id_frasco'), table_name='cassetes')
    op.drop_table('cassetes')
    op.drop_index(op.f('ix_frascos_qr_code'), table_name='frascos')
    op.drop_index(op.f('ix_frascos_id_exame'), table_name='frascos')
    op.drop_index(op.f('ix_frascos_codigo_interno'), table_name='frascos')
    op.drop_table('frascos')
    op.drop_index(op.f('ix_exames_numero_solicitacao'), table_name='exames')
    op.drop_index(op.f('ix_exames_id_paciente'), table_name='exames')
    op.drop_table('exames')
    op.drop_index(op.f('ix_pacientes_local_cpf'), table_name='pacientes_local')
    op.drop_index(op.f('ix_pacientes_local_cns'), table_name='pacientes_local')
    op.drop_table('pacientes_local')
    # ### end Alembic commands ###
